<?php

/**
 * Implementation of hook_init().
 */
function ding_faq_init() {
  //Add our own stylesheet
  drupal_add_css(drupal_get_path('module', 'ding_faq') . '/css/ding_faq.css');
}

/**
 * Implementation of hook_theme_registry_alter.
 */
function ding_faq_theme_registry_alter(&$theme_registry) {
  //We provide our own node templatesso look here as well
  $theme_path = drupal_get_path('module', 'ding_faq') . '/templates';
  $theme_hooks = array('node');
  foreach ($theme_hooks as $hook) {
    $theme_registry[$hook]['theme paths'][] = $theme_path;
  }
}

/**
 * Implementation of hook_nodeapi().
 */
function ding_faq_nodeapi(&$node, $op, $a3 = NULL, $a4 = NULL) {
  // Set default breadcrumb if
  // - viewing a FAQ question node
  // - on a page by itself
  if (($node->type == 'faq_question') &&
      ($op == 'view') && !$a3 && $a4) {
    $trail = array(
      l(t('Home'), '<front>'),
    );

    $trail[] = l(t('FAQ'), 'faq');

    drupal_set_breadcrumb($trail);
  }
}

include_once('ding_faq.features.inc');
